version: 2.0

jobs:

  autofix-biweekly:
    docker:
      - image: gitpod/workspace-full
    steps:
      - run:
          name: Setup CI and install dependencies
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git config --global hub.protocol "https"
            mkdir -p ~/.config
            printf "github.com:\n- user: $GITHUB_LOGIN\n  oauth_token: $GITHUB_TOKEN\n  protocol: https\n" > ~/.config/hub
            printf "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN\n" > ~/.netrc
            brew install hub
            pip install codespell
            npm install -g autofix
      - run:
          name: Run bi-weekly fixes
          environment:
             CRON_TYPE: monthly
          command: |
            echo "[autofix-ci] You're on $PWD"
            ./autofix-agent code-server-boilerplates/starter-pack cdrs-starter-pack
            ./autofix-agent ThePinsTeam/deploy-code-server thepinsteam-internal
            echo "[autofix-ci] Success!"
          no_output_timeout: 120m

  autofix-monthly:
    docker:
      - image: gitpod/workspace-full
    steps:
      - run:
          name: Setup CI and install dependencies
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git config --global hub.protocol "https"
            mkdir -p ~/.config
            printf "github.com:\n- user: $GITHUB_LOGIN\n  oauth_token: $GITHUB_TOKEN\n  protocol: https\n" > ~/.config/hub
            printf "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN\n" > ~/.netrc
            brew install hub
            pip install codespell
            npm install -g autofix
      - run:
          name: Run monthly fixes
          environment:
             CRON_TYPE: monthly
          command: |
            ./run-autofix-agent code-server-boilerplates/template-regostry registry
            echo "Success!"
          no_output_timeout: 120m

workflows:
  version: 2
  biweekly:
    triggers:
      - schedule:
          cron: "30 12 * * 0,3"
          filters:
            branches:
              only:
                - main
    jobs:
      - autofix-biweekly
  monthly:
    triggers:
      - schedule:
          cron: "30 12 9 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - autofix-monthly
