version: 2.0

jobs:
  autofix-weekly:
    docker:
      - image: gitpod/workspace-full # TODO: Use our own image in the future.
    steps:
      - run:
          name: Setup CI and install dependencies
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git config --global hub.protocol "https"
            mkdir -p ~/.config
            printf "github.com:\n- user: $GITHUB_LOGIN\n  oauth_token: $GITHUB_TOKEN\n  protocol: https\n" > ~/.config/hub
            printf "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN\n" > ~/.netrc
            brew install hub
            pip install codespell
            npm install -g autofix
            wget https://raw.githubusercontent.com/code-server-boilerplates/autofix-cronjobs/main/autofix-agent -O /home/gitpod/project/run-autofix
            chmod +x /home/gitpod/project/run-autofix
      - run:
          name: Run bi-weekly fixes
          environment:
             CRON_TYPE: monthly
          command: |
            set -e
            echo "[autofix-ci] You're on $PWD"
            /home/gitpod/project/run-autofix code-server-boilerplates/starter-pack csb-starter-pack
            /home/gitpod/project/run-autofix code-server-boilerplates/starter-pack-as-base-image csb-kubernetes-starter
            /home/gitpod/project/run-autofix code-server-boilerplates/nodejs-starter csb-nodejs-starter
            /home/gitpod/project/run-autofix ThePinsTeam/deploy-code-server thepinsteam-internal
            echo "[autofix-ci] Success!"
          no_output_timeout: 120m
  autofix-monthly:
    docker:
      - image: gitpod/workspace-full
    steps:
      - run:
          name: Setup CI and install dependencies
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git config --global hub.protocol "https"
            mkdir -p ~/.config
            printf "github.com:\n- user: $GITHUB_LOGIN\n  oauth_token: $GITHUB_TOKEN\n  protocol: https\n" > ~/.config/hub
            printf "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN\n" > ~/.netrc
            brew install hub
            pip install codespell
            npm install -g autofix
            wget https://raw.githubusercontent.com/code-server-boilerplates/autofix-cronjobs/main/autofix-agent -O /home/gitpod/project/run-autofix
            chmod +x /home/gitpod/project/run-autofix
      - run:
          name: Run monthly fixes
          environment:
             CRON_TYPE: monthly
          command: |
            echo "[autofix-ci] You're on $PWD"
            ./run-autofix code-server-boilerplates/template-registry registry
            echo "[autofix-ci] Success!"
          no_output_timeout: 120m

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "30 12 * * 6"
          filters:
            branches:
              only:
                - main
    jobs:
      - autofix-weekly
  monthly:
    triggers:
      - schedule:
          cron: "30 12 9 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - autofix-monthly
